### ISSUE TITLE
System.IO.IOException : The handle is invalid - GitHub Actions, Windows

### ISSUE THREAD

**Issue by eduherminio** [spectresystems/spectre.console#151]
I'm using `spectre.console` in a library ([this file](https://github.com/eduherminio/AoCHelper/blob/pretty-console/src/AoCHelper/Solver.cs)) and I have a test project that runs [simple tests](https://github.com/eduherminio/AoCHelper/blob/pretty-console/tests/AoCHelper.Test/OverrideInputFileExtensionTests.cs) over it.

Everything works like a charm locally in both Windows and Linux but I have a CI pipeline configured using GitHub Actions, and tests are failing there in `windows-latest` agents.
[This is the failed run](https://github.com/eduherminio/AoCHelper/runs/1467388633). I also tried using `pwsh` as shell, but [same result](https://github.com/eduherminio/AoCHelper/runs/1467460306).

From what I understand, it's failing [when invoking `Console.Clear();`](https://github.com/eduherminio/AoCHelper/blob/pretty-console/src/AoCHelper/Solver.cs#L130), which I do before rendering a table:
```csharp
table.AddRow(problemTitle, $"Part {part}", solution, $"[{color}]{elapsedTime}[/]");

Console.Clear();
AnsiConsole.Render(table);
```

PD:
I'm trying to use `Console.Clear()` because using `AnsiConsole.Console.Clear()` works for the animation of the table rows being populated, but floods `stdout` with partial tables when scrolling up after the program is run.
Am I missing a better way of doing it?

Final result (it can be tested in [this project](https://github.com/eduherminio/AoCHelper/tree/pretty-console/src/AoCHelper.PoC)):
![image](https://user-images.githubusercontent.com/11148519/100517610-0987a880-318c-11eb-897d-6278a440fd44.png)

But when scrolling up:
![image](https://user-images.githubusercontent.com/11148519/100517585-d3e2bf80-318b-11eb-8c67-1494b784e5a3.png)

**Comment by patriksvensson** [comment]
Console.Clear() won't work in places like GitHub actions on a Windows machine, since there isn't an actual console handle to clear and will throw. AnsiConsole.Clear will use ANSI escape sequences to clear the screen, however, not sure if this is supported on GitHub and is probably why you see strange output there.

I think your best approach here is to try to detect whether or not running in an non-interactive environment and not run the clear call at all.

**Comment by eduherminio** [comment]
> I think your best approach here is to try to detect whether or not running in an non-interactive environment and not run the clear call and animations at all.

hmm making the tests in this repo pass is relatively easy, but my real issue here is that I'm using this code as part of a NuGet package.

If I use `<DefineConstants>` depending on env variables + preprocessor, I'll get await with it in this repo, but other projects that will use of this package won't be able to get around the problem when using non-interactive environments, right?

Can you think of any way around it?

**Comment by patriksvensson** [comment]
Environment.Interactive in combination with the environment variables CI servers define should be enough.

**Comment by eduherminio** [comment]
hmm that's the key, I was missing the point by using the environment variables at compile time rather than at runtime.
Thanks a lot (and congrats on the project!).

**Comment by antibarbie** [comment]
We just hit the same problem, when running spectre output in a gitlab runner.

Maybe this could be patched/tested in spectre library directly ?  so that programs would run safely whether they are running in hostile environments or not.

it feels wrongs to throw IOException just because output is redirected..   
Ok I stop the rant, shall I propose a pull request if I have time ?
