### ISSUE TITLE
Have a project with common concepts between spectre.console and spectre.cli

### ISSUE THREAD

**Issue by gsferreira** [spectresystems/spectre.console#168]
I have a project using spectre.cli and now I want to add spectre.console to it, in order to improve the user experience.

I noticed that a concept like "ValidationResult" exists in both projects, so, it will exist in both namespaces.

I see the potential of using both projects together, so I have been thinking if it wouldn't be a good idea to have a "core" project with base concepts common to both (like the ValidationResult).

Sorry if this is not the best place to give this kind of feedback since it impacts both projects.

**Comment by patriksvensson** [comment]
@gsferreira Thanks for the suggestion!

I however want to keep the two projects separate and don't want them to rely on shared definitions since this will make it more difficult to change things in the future and I don't want the cognitive overhead it would impose. One solution to this could be to rename the `ValidationResult` class in one library to something else. I will think about it.
