### ISSUE TITLE
ProgressTask.Stop() does not work properly

### ISSUE THREAD

**Issue by Yaroshvitaliy** [spectresystems/spectre.console#279]
ProgressTask.Stop() does not stop progress task completely, it remain be running (spinner is active). The only way to finish the task is to set 100% progress that is not acceptable for my task. And the actual problem is that this progress is being rendered over the rest UI, including other instances of progresses, that makes the following issue critical:
https://github.com/spectresystems/spectre.console/issues/259

**Comment by phil-scott-78** [comment]
I agree, that does seem like unexpected behavior. Without context on why you are stopping the tasks I want to clarify a couple of things with you before we start planning a fix. 

Currently a lot of assumptions are made about a task. It is either waiting to be started, running, or finished. Once a task is finished you can't return to running or started. This is important because it not only drives UI (e.g. like you are seeing with the spinner), but also for concepts like when a Progress bar itself knows when all its children are completed so it knows when to finish itself.  There is no concept of a paused task beyond just a progress bar that isn't actively getting its `Increment` method called

So, for this bug I'd propose a couple of changes to `ProgressTask`

1. Change `IsFinished` to `StopTime != null || Value >= MaxValue`. 
2. Throw an exception on `StartTask` if `StopTime != null`. Without this being explicit 
3. Add documentation to `StopTask` indicating that it can't be started again

This would obviously be a breaking behavior, but I suspect with no one having submitted this bug before I think it's a safe assumption not a lot of people are stopping and starting tasks because they surely would have noticed this bug.

**Comment by Yaroshvitaliy** [comment]
Thank you for your reply. 
I agree that `IsFinished ` should consider `StopTime != null`.
I think no one has submitted this bug before simply because it's realy rare case when it's needed to stop ptogress task.

I've found such a workaround as a temporary solution for a stopped progress task.
1. increment the progress task to set progress 100% - this will stop the task 
2. set progress' task description like 'stopped: {task.Percentage}%'

This is not an ideal solution, but it's critical to me to show when progress task was stopped.

**Comment by bddckr** [comment]
In my particular case I have a task that can actually be skipped altogether. As it's one task of many, I still want to have it in the progress' tasks list - visible to the user. In this sense I believe my requirements match @Yaroshvitaliy's: We need the ability to stop a task and freeze it's progress to ensure we do not lose the percentage information.

So currently what I do is I set the task description to `+= "(skipped)"` and then to make the task stop properly I do `task.Value = task.MaxValue`. That is the easiest way I found to ensure a task is stopped.

It sounds like this proposed change would take care of allowing tasks to stop without reaching completion. Am I reading that right?
> 1. Change IsFinished to `StopTime != null || Value >= MaxValue`.

**Comment by Yaroshvitaliy** [comment]
@bddckr Yes, I think `IsFinished  => StopTime != null || Value >= MaxValue` will solve the problem, but it needs to be checked.

**Comment by phil-scott-78** [comment]
@bddckr, you got it. Rather than change the Value you'd be calling `StopTask()`. 

I appreciate your input here, never easy to decide to change behavior but the more feedback certainly helps make sure expectations are getting matched.
