### ISSUE TITLE
Maybe bug with signle curly braces and EscapeMarkup

### ISSUE THREAD

**Issue by 0xF6** [spectresystems/spectre.console#287]
**Information**
 - OS: Windows 10, 10.0.21313
 - Version: 0.37.0
 - Terminal: Windows Terminal, conhost

**Describe the bug**
Using curly braces symbol in the source text causes the "Input string was not in a correct format" exception when calling the MarkupLine function.
And function EscapeMarkup is not escape curly braces symbol.

**To Reproduce**
 ```
 var escapedText = "{".EscapeMarkup();
 MarkupLine($"[red bold]{escapedText}[/]");
 ```

**Expected behavior**
Success rendering

**Additional context**
I understand that `{` symbol is used in formatting when placing arguments passed to the `MarkupLine` function.
And probably this is solved by the usual extension for a string that will safely wrap symbol `{` into `{{`.
But still, I would like to know if this exception is correct?

**Comment by phil-scott-78** [comment]
Hmmm, I suspect you are right this is a bug but maybe not the one you are targeting. The bracket isn't markdown, so it won't ever be escaped. We can actually shorten this right down to 

```csharp
MarkupLine("{");
```
and see the same thing "Input string was not in a correct format".

I believe the root cause is we are implicitly calling string.Format on the input string even when there are no args to format which is causing the need to escape the brackets. This behavior differs from what you'd see from the regular `Console.WriteLine` so I think it's definitely work investigating a fix.

Good find!

**Comment by phil-scott-78** [comment]
@patriksvensson - two options to fix. Either a simple if statement or a bunch of overloads.

```csharp
/// <summary>
/// Writes the specified markup to the console.
/// </summary>
/// <param name="console">The console to write to.</param>
/// <param name="provider">An object that supplies culture-specific formatting information.</param>
/// <param name="format">A composite format string.</param>
/// <param name="args">An array of objects to write.</param>
public static void Markup(this IAnsiConsole console, IFormatProvider provider, string format, params object[] args)
{
    string s = args == null || args.Length == 0 ? format : string.Format(provider, format, args);
    console.Render(MarkupParser.Parse(s));
}
```

I'm tempated to go the overload route just to avoid allocations and be a bit more explicit about the usage, but it would double the amount of code in this method so I wanted to run it by you first.

**Comment by patriksvensson** [comment]
@phil-scott-78 Yeah, I think that the overload makes sense here as well
